import pygame

# GameArena
TILE_CLICKED = pygame.USEREVENT+1

FIRE = pygame.USEREVENT+2
ENEMY_HIT = pygame.USEREVENT+3
ENEMY_KILLED = pygame.USEREVENT+4

NEW_ENEMY_WAVE = pygame.USEREVENT + 5
ENEMY_COMPLETED_PATH = pygame.USEREVENT+6
